export interface QuranVerse {
  text: string;
  surah: string;
  verse: string;
  revelation: "Meccan" | "Medinan";
  theme: string;
}

export const quranVerses: QuranVerse[] = [
  {
    text: "And We have certainly made the Quran easy to remember, so is there anyone who will be mindful?",
    surah: "Al-Qamar",
    verse: "54:17",
    revelation: "Meccan",
    theme: "Quran",
  },
  {
    text: "Indeed, with hardship comes ease. Indeed, with hardship comes ease.",
    surah: "Ash-Sharh",
    verse: "94:5-6",
    revelation: "Meccan",
    theme: "Ease",
  },
  {
    text: "So remember Me; I will remember you. And be grateful to Me and do not deny Me.",
    surah: "Al-Baqarah",
    verse: "2:152",
    revelation: "Medinan",
    theme: "Gratitude",
  },
  {
    text: "And whoever puts their trust in Allah, He is sufficient for them.",
    surah: "At-Talaq",
    verse: "65:3",
    revelation: "Medinan",
    theme: "Trust",
  },
  {
    text: "And We have not sent you, O Muhammad, except as a mercy to the worlds.",
    surah: "Al-Anbiya",
    verse: "21:107",
    revelation: "Meccan",
    theme: "Mercy",
  },
  {
    text: "And your Lord says: Call upon Me; I will respond to you.",
    surah: "Ghafir",
    verse: "40:60",
    revelation: "Meccan",
    theme: "Prayer",
  },
  {
    text: "And whoever does good, it is for their own soul; and whoever does evil, it is against it.",
    surah: "Fussilat",
    verse: "41:46",
    revelation: "Meccan",
    theme: "Accountability",
  },
  {
    text: "He is with you wherever you are. And Allah sees what you do.",
    surah: "Al-Hadid",
    verse: "57:4",
    revelation: "Medinan",
    theme: "Presence",
  },
  {
    text: "And whoever does an atom's weight of good will see it. And whoever does an atom's weight of evil will see it.",
    surah: "Az-Zalzalah",
    verse: "99:7-8",
    revelation: "Medinan",
    theme: "Accountability",
  },
  {
    text: "And your Lord has decreed that you worship none but Him, and that you be good to your parents.",
    surah: "Al-Isra",
    verse: "17:23",
    revelation: "Meccan",
    theme: "Kindness",
  },
  {
    text: "And do not walk upon the earth exultantly. Indeed, you will never tear the earth apart, nor reach the mountains in height.",
    surah: "Al-Isra",
    verse: "17:37",
    revelation: "Meccan",
    theme: "Humility",
  },
  {
    text: "Indeed, Allah orders justice and good conduct and giving to relatives and forbids immorality and bad conduct and oppression.",
    surah: "An-Nahl",
    verse: "16:90",
    revelation: "Meccan",
    theme: "Justice",
  },
  {
    text: "And We have certainly created man and We know what his soul whispers to him, and We are closer to him than his jugular vein.",
    surah: "Qaf",
    verse: "50:16",
    revelation: "Meccan",
    theme: "Closeness",
  },
  {
    text: "And the servants of the Most Merciful are those who walk upon the earth humbly, and when the ignorant address them, they say: Peace.",
    surah: "Al-Furqan",
    verse: "25:63",
    revelation: "Meccan",
    theme: "Humility",
  },
  {
    text: "Indeed, the patient will be given their reward without account.",
    surah: "Az-Zumar",
    verse: "39:10",
    revelation: "Meccan",
    theme: "Patience",
  },
  {
    text: "And if you should count the favors of Allah, you could not enumerate them.",
    surah: "An-Nahl",
    verse: "16:18",
    revelation: "Meccan",
    theme: "Gratitude",
  },
  {
    text: "Indeed, prayer prohibits immorality and wrongdoing, and the remembrance of Allah is greater.",
    surah: "Al-Ankabut",
    verse: "29:45",
    revelation: "Meccan",
    theme: "Prayer",
  },
  {
    text: "And whoever fears Allah, He will make for them a way out, and will provide for them from where they do not expect.",
    surah: "At-Talaq",
    verse: "65:2-3",
    revelation: "Medinan",
    theme: "Provision",
  },
  {
    text: "O mankind, indeed We have created you from male and female and made you peoples and tribes that you may know one another. Indeed, the most noble of you in the sight of Allah is the most righteous.",
    surah: "Al-Hujurat",
    verse: "49:13",
    revelation: "Medinan",
    theme: "Unity",
  },
  {
    text: "And those who have believed and done righteous deeds — We will surely assign to them the highest gardens beneath which rivers flow, wherein they abide forever.",
    surah: "An-Nisa",
    verse: "4:122",
    revelation: "Medinan",
    theme: "Paradise",
  },
  {
    text: "And the Hereafter is better for you than the first life. And your Lord is going to give you, and you will be satisfied.",
    surah: "Ad-Duha",
    verse: "93:4-5",
    revelation: "Meccan",
    theme: "Hope",
  },
  {
    text: "And whoever emigrates for the cause of Allah will find on the earth many places of refuge and abundance.",
    surah: "An-Nisa",
    verse: "4:100",
    revelation: "Medinan",
    theme: "Courage",
  },
  {
    text: "Never will you attain righteousness until you spend from that which you love.",
    surah: "Aal-Imran",
    verse: "3:92",
    revelation: "Medinan",
    theme: "Charity",
  },
  {
    text: "And the earth — We have spread it out and set therein firm mountains, and caused to grow therein every beautiful kind.",
    surah: "Qaf",
    verse: "50:7",
    revelation: "Meccan",
    theme: "Creation",
  },
  {
    text: "And He found you lost and guided you. And He found you poor and enriched you.",
    surah: "Ad-Duha",
    verse: "93:7-8",
    revelation: "Meccan",
    theme: "Gratitude",
  },
  {
    text: "Say: O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins.",
    surah: "Az-Zumar",
    verse: "39:53",
    revelation: "Meccan",
    theme: "Forgiveness",
  },
  {
    text: "And the sky We constructed with strength, and indeed We are the expander of it.",
    surah: "Adh-Dhariyat",
    verse: "51:47",
    revelation: "Meccan",
    theme: "Creation",
  },
  {
    text: "And He is with you wherever you are. And Allah sees what you do.",
    surah: "Al-Hadid",
    verse: "57:4",
    revelation: "Medinan",
    theme: "Presence",
  },
  {
    text: "Indeed, we belong to Allah, and indeed to Him we will return.",
    surah: "Al-Baqarah",
    verse: "2:156",
    revelation: "Medinan",
    theme: "Patience",
  },
  {
    text: "So which of the favors of your Lord would you deny?",
    surah: "Ar-Rahman",
    verse: "55:13",
    revelation: "Medinan",
    theme: "Gratitude",
  },
];
